---
name: Check (Ruff)

on:
  push:
    branches:
      - main
      - test
    paths-ignore:
      - "**/README.md"

jobs:
  check_py:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v2

  check_js:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'

      - name: Install dev dependencies
        run: npm install

      - name: Run eslint
        run: npm run lint
